version: "3.8"

services:

  config-service:
    build: ./config-service
    ports:
      - "9090:9090"
  backempresa-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=backempresa
  back-web:
    image: postgres
    restart: always
    ports:
      - 5031:5031
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=backweb
    command: -p 5031