version: "3.8"

services:
  config-service:
    build: ./config-service
    ports:
      - "9090:9090"

  eureka-service:
    container_name: eureka
    build:
      context: ./eureka-service
      dockerfile: Dockerfile
    ports:
      - "9292:9292"
    depends_on:
      - config-service


  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"

