version: "3.8"

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  config-service:
    build: ./config-service
    ports:
      - "9090:9090"
    expose:
      - "9090"

  eureka-server:
    build: ./eureka-service
    ports:
      - "9292:9292"
    environment:
      CLOUD_SEA_CONFIG_SERVER_URI: http://config-service:9090
      EUREKA_DEFAULT_ZONE_URL: http://eureka-server:9292/eureka/
    depends_on:
    - config-service
    links:
      - config-service:config-service
  backempresa-db:
    container_name: backempresa-db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=backempresa

  back-web:
      container_name: backweb-db
      image: postgres
      restart: always
      ports:
        - 5031:5031
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=backweb
      command: -p 5031

  email-db:
      image: postgres
      restart: always
      ports:
        - 5444:5444
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=emails
      command: -p 5444

  backempresa-service:
      container_name: backempresa
      build: ./back-empresa
      environment:
        SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
        CLOUD_SEA_CONFIG_SERVER_URI: http://config-service:9090
        EUREKA_DEFAULT_ZONE_URL: http://eureka-server:9292/eureka/
        DATABASE_URL: jdbc:postgresql://backempresa-db:5432/backempresa
        FEIGN_CLIENT_URL: http://backweb:8084/api/v0

      ports:
        - "8085:8085"
      depends_on:
        - backempresa-db
        - config-service
        - kafka
        - eureka-server
      links:
          - config-service:config-service
          - eureka-server:eureka-server
          - backempresa-db:backempresa-db


  backweb-service:
      container_name: backweb
      build: ./back-web
      environment:
        SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
        CLOUD_SEA_CONFIG_SERVER_URI: http://config-service:9090
        EUREKA_DEFAULT_ZONE_URL: http://eureka-server:9292/eureka/
        DATABASE_URL: jdbc:postgresql://backweb-db:5031/backweb
      ports:
        - "8084:8084"
      depends_on:
        - back-web
        - config-service
        - kafka
        - eureka-server
      links:
        - config-service:config-service
        - eureka-server:eureka-server
        - back-web:backweb
  email-service:
    container_name: emails
    build: ./back-web
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
      CLOUD_SEA_CONFIG_SERVER_URI: http://config-service:9090
      EUREKA_DEFAULT_ZONE_URL: http://eureka-server:9292/eureka/
      DATABASE_URL: jdbc:postgresql://backweb-db:5444/emails
    ports:
      - "8084:8084"
    depends_on:
      - email-db
      - config-service
      - kafka
      - eureka-server
    links:
      - config-service:config-service
      - eureka-server:eureka-server
      - email-db:email-db








