version: "3.8"
services:
  config-service:
    build: ./config-service
    ports:
      - "9090:9090"

  eureka-service:
    build: ./eureka-service
    ports:
      - "9292:9292"
    environment:
      eureka.instance.hostname: eureka-server
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"

