server:
    port: 8081
spring:
    datasource:
        platform: postgres
        url: jdbc:postgresql://localhost:5444/emails
        username: postgres
        password: postgres
        hikari:
            connectionTimeout: 20000
            maximumPoolSize: 5
    jpa:
        hibernate:
            ddl-auto: create

    kafka:
        consumer:
            auto-offset-reset: earliest
            bootstrap-server: localhost:9092
            group:
                id: email
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            properties:
                spring:
                    json:
                        trusted:
                            packages: '*'
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        topic:
            name: reservas_topic
spring.mail:
    port: 587
    host: smtp.gmail.com
    username: robin.bucad6@gmail.com
    password: hijbfewpmfuuvtgo
    test-connection: false
    default-encoding: UTF-8
    properties:
        mail:
            debug: false
            smtp:
                timeout: 5000
                ssl:
                    enable: false
                socketFactory:
                    port:
                    class:
                auth: true
                starttls:
                    enable: true
                    required: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9292/eureka/