server:
  port: 8080


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9292/eureka/
  
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: backempresa-service
          uri: lb://backempresa-service
          predicates:
            - Path=/api/**
        - id: backweb-service
          uri: lb://backweb-service
          predicates:
            - Path=/api/**
        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/api/**
        - id: gateway-service
          uri: lb://gateway-service
          predicates:
            Path=/**