server:
  port: 8080


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE_URL:http://localhost:9292/eureka/}
  
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: BACKEMPRESA-SERVICE
          uri: lb://BACKEMPRESA-SERVICE
          predicates:
            - Path=/api/v0/busesEmpresa/** , /api/v0/checkSecurity/** , /api/v0/personas/** , /api/v0/login/**
        - id: BACKWEB-SERVICE
          uri: lb://BACKWEB-SERVICE
          predicates:
            - Path=/api/v0/reservasWeb/** , /api/v0/reservasDisponiblesWeb/** 
       