server:
  port: 9090

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Robinbucad/VIRTUAL-BUS.git
          searchPaths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
  security:
    user:
      name: root
      password: s3cr3t